game:
  rounds: 2
  rounds_to_win: 6
  rounds_per_side: 5

  buy_time: 15
  warmup_time: 30
  round_time: 120
  round_won_money: 500
  round_lost_money: 250

  bomb_plant_time: 3
  bomb_defuse_time: 10
  bomb_explotion_time: 45
  bomb_explotion_radius: 10
  bomb_explotion_damage: 1000
  bomb_plant_money: 500
  bomb_defuse_money: 500

player:
  health: 100
  initial_money: 1000
  movement_speed: 1.0

weapons:
  knife:
    max_ammo: 0
    initial_ammo: 0
    damage_per_bullet: 20
    precision: 1.0
    cost: 0
    range: 1
    bullets_per_shot: 0
    fire_rate: 0.3
    bounty_money: 1500
    reload_time: 0

  glock:
    max_ammo: 120
    initial_ammo: 20
    damage_per_bullet: 25
    precision: 0.8
    cost: 0
    range: 4
    bullets_per_shot: 1
    fire_rate: 0.4
    bounty_money: 300
    reload_time: 2.2

  ak-47:
    max_ammo: 90
    initial_ammo: 30
    damage_per_bullet: 20
    precision: 0.7
    cost: 2700
    range: 6
    bullets_per_shot: 3
    fire_rate: 0.2
    bounty_money: 300
    reload_time: 2.5

  m3:
    max_ammo: 32
    initial_ammo: 8
    damage_per_bullet: 15
    precision: 0.6
    cost: 1700
    range: 3
    bullets_per_shot: 1
    fire_rate: 0.8
    bounty_money: 300
    reload_time: 3.0

  awp:
    max_ammo: 30
    initial_ammo: 5
    damage_per_bullet: 100
    precision: 1.0
    cost: 4750
    range: 100
    bullets_per_shot: 1
    fire_rate: 1.3
    bounty_money: 300
    reload_time: 3.7

fov:
  angle: 45
  ratio: 40
  opacity: 153

display:
  width: 580
  height: 400