#ifndef CLIENT_GAME_ASSET_BACKGROUND_ID_H
#define CLIENT_GAME_ASSET_BACKGROUND_ID_H

namespace Model {
enum BackgroundID {
    BG_DARK_GREEN = 0x00,
    BG_SMOOTH_GREEN = 0x01,
    BG_YELLOW = 0x02,

    NO_BACKGROUND = 0xFF
};
};

#endif // CLIENT_GAME_ASSET_BACKGROUND_ID_H
